import type { createClient } from "@/lib/supabase/server";
import type { ActionApproval, AutonomyLevel, AutonomyPolicy, Capability, IntegrationAction, IntegrationConnection, JsonObject } from "../core/types";
import type { IntegrationStore } from "../core/store";
import { sanitize } from "../security/sanitize";

type DbClient = Awaited<ReturnType<typeof createClient>>;
type Row = Record<string, unknown>;
const text = (value: unknown) => typeof value === "string" ? value : "";
const object = (value: unknown) => value && typeof value === "object" && !Array.isArray(value) ? value as JsonObject : {};
const list = (value: unknown) => Array.isArray(value) ? value.map(String) : [];
const autonomyMap: Record<string, AutonomyLevel> = { observe: "observe_only", autonomous: "automatic", blocked: "observe_only", observe_only: "observe_only", suggest: "suggest", approval_required: "approval_required", automatic: "automatic", automatic_with_limits: "automatic_with_limits" };

export class SupabaseIntegrationStore implements IntegrationStore {
  constructor(private readonly db: DbClient) {}
  async listConnections(organizationId: string): Promise<IntegrationConnection[]> {
    const { data, error } = await this.db.from("integrations").select("*").eq("organization_id", organizationId);
    if (error) throw error;
    return (data as Row[]).map((row) => ({ id: text(row.id), organizationId: text(row.organization_id), provider: text(row.provider), status: text(row.status) as IntegrationConnection["status"], accountIdentifier: text(row.account_identifier) || undefined, scopes: list(row.scopes), capabilities: list(row.capabilities) as Capability[], credentialsReference: text(row.credentials_reference) || undefined, priority: Number(row.priority ?? 0), createdAt: text(row.connected_at) || text(row.updated_at), updatedAt: text(row.updated_at), lastSyncAt: text(row.last_sync_at) || undefined, tokenExpiresAt: text(row.token_expires_at) || undefined, metadata: object(row.metadata), health: object(row.health) as IntegrationConnection["health"] }));
  }
  async hasPermission(org: string, employee: string, capability: Capability) { const { data, error } = await this.db.from("employee_permissions").select("allowed").eq("organization_id", org).eq("employee_id", employee).eq("capability", capability).eq("allowed", true).maybeSingle(); if (error) throw error; return Boolean(data); }
  async listAutonomyPolicies(org: string, employee: string, capability: Capability): Promise<AutonomyPolicy[]> {
    const { data, error } = await this.db.from("employee_autonomy_policies").select("*").eq("organization_id", org).eq("active", true).in("action_key", [capability, "*"]).or(`employee_id.eq.${employee},employee_id.is.null`); if (error) throw error;
    return (data as Row[]).map((row) => ({ id: text(row.id), organizationId: text(row.organization_id), employeeId: text(row.employee_id) || undefined, capability: text(row.action_key) as Capability | "*", level: autonomyMap[text(row.mode)] ?? "approval_required", limits: object(row.limits) as AutonomyPolicy["limits"], active: Boolean(row.active) }));
  }
  private mapAction(row: Row): IntegrationAction { return { id: text(row.id), organizationId: text(row.organization_id), employeeId: text(row.employee_id), taskId: text(row.task_id) || undefined, connectionId: text(row.connection_id), provider: text(row.provider), capability: text(row.capability) as Capability, idempotencyKey: text(row.idempotency_key), input: object(row.input_data), status: text(row.status) as IntegrationAction["status"], approvalId: text(row.approval_id) || undefined, output: row.output_data, externalId: text(row.external_id) || undefined, error: row.error_data as IntegrationAction["error"], createdAt: text(row.created_at), completedAt: text(row.completed_at) || undefined }; }
  async reserveAction(action: IntegrationAction) {
    const row = { id: action.id, organization_id: action.organizationId, employee_id: action.employeeId, task_id: action.taskId, connection_id: action.connectionId, provider: action.provider, capability: action.capability, idempotency_key: action.idempotencyKey, input_data: sanitize(action.input), status: action.status, created_at: action.createdAt };
    const { data, error } = await this.db.from("integration_actions").insert(row).select().maybeSingle();
    if (!error && data) return { created: true, action: this.mapAction(data as Row) };
    if (error?.code !== "23505") throw error;
    const { data: existing, error: findError } = await this.db.from("integration_actions").select("*").eq("organization_id", action.organizationId).eq("idempotency_key", action.idempotencyKey).single(); if (findError) throw findError; return { created: false, action: this.mapAction(existing as Row) };
  }
  async updateAction(org: string, id: string, changes: Partial<IntegrationAction>) { const row: Row = {}; if (changes.status) row.status = changes.status; if (changes.approvalId) row.approval_id = changes.approvalId; if (changes.output !== undefined) row.output_data = sanitize(changes.output); if (changes.externalId) row.external_id = changes.externalId; if (changes.error) row.error_data = sanitize(changes.error); if (changes.completedAt) row.completed_at = changes.completedAt; const { data, error } = await this.db.from("integration_actions").update(row).eq("organization_id", org).eq("id", id).select().single(); if (error) throw error; return this.mapAction(data as Row); }
  async getAction(org: string, id: string) { const { data, error } = await this.db.from("integration_actions").select("*").eq("organization_id", org).eq("id", id).maybeSingle(); if (error) throw error; return data ? this.mapAction(data as Row) : undefined; }
  private mapApproval(row: Row): ActionApproval { const statusMap: Record<string, ActionApproval["status"]> = { pendente: "pending", aprovada: "approved", recusada: "rejected", expirado: "expired", executada: "executed", falhou: "failed", pending: "pending", approved: "approved", rejected: "rejected", expired: "expired", executed: "executed", failed: "failed" }; return { id: text(row.id), organizationId: text(row.organization_id), employeeId: text(row.employee_id), taskId: text(row.task_id) || undefined, actionId: text(row.integration_action_id), capability: text(row.capability) as Capability, provider: text(row.provider), description: text(row.description), sanitizedPayload: object(row.payload), reason: text(row.reason), riskLevel: text(row.risk_level) === "alto" ? "high" : text(row.risk_level) === "medio" ? "medium" : "low", status: statusMap[text(row.integration_status) || text(row.status)] ?? "pending", requestedAt: text(row.requested_at) }; }
  async createApproval(approval: ActionApproval) { const { data, error } = await this.db.from("approvals").insert({ id: approval.id, organization_id: approval.organizationId, employee_id: approval.employeeId, task_id: approval.taskId, integration_action_id: approval.actionId, action_type: approval.capability, capability: approval.capability, provider: approval.provider, title: `Aprovar ${approval.capability}`, description: approval.description, impact: approval.reason, reason: approval.reason, risk_level: approval.riskLevel === "high" ? "alto" : approval.riskLevel === "medium" ? "medio" : "baixo", payload: sanitize(approval.sanitizedPayload), status: "pendente", idempotency_key: `integration-action:${approval.actionId}` }).select().single(); if (error) throw error; return this.mapApproval(data as Row); }
  async getApproval(org: string, id: string) { const { data, error } = await this.db.from("approvals").select("*").eq("organization_id", org).eq("id", id).maybeSingle(); if (error) throw error; return data ? this.mapApproval(data as Row) : undefined; }
  async updateApproval(org: string, id: string, changes: Partial<ActionApproval>) { const reverse: Record<string, string> = { pending: "pendente", approved: "aprovada", rejected: "recusada", expired: "expirado", executed: "executada", failed: "falhou" }; const { data, error } = await this.db.from("approvals").update(changes.status ? { integration_status: changes.status, status: ["pending", "approved", "rejected"].includes(changes.status) ? reverse[changes.status] : undefined } : {}).eq("organization_id", org).eq("id", id).select().single(); if (error) throw error; return this.mapApproval(data as Row); }
  async recordAudit(input: Parameters<IntegrationStore["recordAudit"]>[0]) { const { error } = await this.db.from("audit_logs").insert({ organization_id: input.organizationId, actor_id: input.employeeId, action: input.capability, entity_type: "integration_action", entity_id: input.actionId, after_data: sanitize({ provider: input.provider, taskId: input.taskId, status: input.status, input: input.input, output: input.output, error: input.error, durationMs: input.durationMs, source: input.source }) }); if (error) throw error; }
  async recordActivity(input: Parameters<IntegrationStore["recordActivity"]>[0]) { const { error } = await this.db.from("activities").insert({ organization_id: input.organizationId, employee_id: input.employeeId, task_id: input.taskId, activity_type: "integration_action", title: input.title, description: input.description, metadata: sanitize(input.metadata ?? {}), source: "integration_engine" }); if (error) throw error; }
}
