import type { Activity, Approval, DemoState, Employee, FinancialAccount, Integration, Task } from "@/types/domain";

export const employees: Employee[] = [
  { id: "ana", name: "Ana", initials: "AN", role: "Assistente Administrativa e Financeira", department: "Financeiro", level: "Especialista", description: "Organiza a operação administrativa, mantém o caixa sob controle, acompanha pendências e prepara ações financeiras para sua aprovação.", status: "aguardando aprovação", currentTask: "Preparando cobranças em atraso", tasksCompleted: 148, performance: 96, successRate: 98, averageTime: "8 min", savings: 18420, monthlyPrice: 149, hired: true, color: "#8b5cf6", skills: ["Gestão documental", "Fluxo de caixa", "Contas a pagar e receber", "Cobranças", "Conciliação", "Controle de vencimentos"], responsibilities: ["Classificar e relacionar documentos administrativos e financeiros", "Extrair dados de notas, boletos, recibos e comprovantes", "Acompanhar contas a pagar, receber e vencimentos", "Identificar duplicidades, inconsistências e documentos faltantes", "Preparar cobranças e encaminhamentos com aprovação", "Gerar resumos, projeções e relatórios financeiros"], tools: ["Gmail", "Google Calendar", "Google Drive", "ERP Alpha", "Gerador de cobrança"] },
  { id: "carlos", name: "Carlos", initials: "CA", role: "Comprador Digital", department: "Compras", level: "Pleno", description: "Compara fornecedores e transforma listas de materiais em recomendações claras de compra.", status: "trabalhando", currentTask: "Comparando 3 fornecedores", tasksCompleted: 87, performance: 92, successRate: 94, averageTime: "14 min", savings: 12600, monthlyPrice: 99, hired: true, color: "#3b82f6", skills: ["Cotações", "Fornecedores", "Negociação", "Pedidos"], responsibilities: ["Buscar e comparar fornecedores", "Analisar preço, prazo e condições", "Preparar recomendações de compra"], tools: ["Catálogo de fornecedores", "ERP Alpha"] },
  { id: "sofia", name: "Sofia", initials: "SO", role: "Atendimento Digital", department: "Atendimento", level: "Pleno", description: "Organiza solicitações e ajuda clientes com respostas rápidas, consistentes e cuidadosas.", status: "trabalhando", currentTask: "Classificando 12 mensagens", tasksCompleted: 326, performance: 95, successRate: 97, averageTime: "3 min", savings: 9200, monthlyPrice: 99, hired: true, color: "#06b6d4", skills: ["Triagem", "Atendimento", "FAQs", "Encaminhamento"], responsibilities: ["Organizar mensagens recebidas", "Responder dúvidas simples", "Encaminhar casos complexos"], tools: ["WhatsApp", "Gmail"] },
  { id: "julia", name: "Júlia", initials: "JU", role: "Marketing Digital", department: "Marketing", level: "Pleno", description: "Transforma objetivos comerciais em pautas, campanhas e um calendário consistente.", status: "disponível", currentTask: "Sem tarefa no momento", tasksCompleted: 64, performance: 90, successRate: 93, averageTime: "22 min", savings: 7800, monthlyPrice: 99, hired: true, color: "#ec4899", skills: ["Conteúdo", "Campanhas", "Calendário", "Revisão"], responsibilities: ["Sugerir pautas", "Produzir e revisar textos", "Preparar campanhas para aprovação"], tools: ["Google Drive", "Calendário"] },
  { id: "lucas", name: "Lucas", initials: "LU", role: "Comercial Digital", department: "Comercial", level: "Pleno", description: "Mantém o funil ativo, qualifica oportunidades e não deixa nenhum lead promissor esfriar.", status: "disponível", currentTask: "Sem tarefa no momento", tasksCompleted: 112, performance: 93, successRate: 95, averageTime: "6 min", savings: 15300, monthlyPrice: 119, hired: true, color: "#f59e0b", skills: ["Leads", "Qualificação", "Follow-up", "Funil"], responsibilities: ["Organizar e qualificar leads", "Acompanhar follow-ups", "Identificar oportunidades paradas"], tools: ["CRM Alpha", "Gmail"] },
  { id: "fiscal", name: "Marta", initials: "MA", role: "Especialista Fiscal", department: "Financeiro", level: "Sênior", description: "Revisa obrigações e organiza documentos fiscais com rastreabilidade.", status: "disponível", currentTask: "Ainda não contratada", tasksCompleted: 0, performance: 97, successRate: 97, averageTime: "12 min", savings: 0, monthlyPrice: 189, hired: false, color: "#10b981", skills: ["Tributos", "Obrigações", "Documentos fiscais"], responsibilities: ["Revisar documentos", "Mapear obrigações", "Sinalizar riscos"], tools: ["ERP", "Drive"] },
  { id: "imob", name: "Rafael", initials: "RA", role: "Vendedor Imobiliário", department: "Comercial", level: "Especialista", description: "Qualifica compradores e acompanha oportunidades imobiliárias.", status: "disponível", currentTask: "Ainda não contratado", tasksCompleted: 0, performance: 94, successRate: 94, averageTime: "5 min", savings: 0, monthlyPrice: 169, hired: false, color: "#6366f1", skills: ["Imóveis", "Qualificação", "Follow-up"], responsibilities: ["Qualificar interessados", "Agendar visitas", "Atualizar o funil"], tools: ["CRM", "WhatsApp"] },
];

export const tasks: Task[] = [
  { id: "task-ana-1", employeeId: "ana", title: "Analisar vencimentos dos próximos 7 dias", description: "Analise as contas que vencem nos próximos sete dias e prepare as cobranças dos clientes atrasados.", priority: "alta", status: "aguardando aprovação", dueAt: "Hoje, 17:00", requiresApproval: true, createdAt: "Hoje, 08:42", result: "12 contas analisadas · R$ 48.920 a vencer · 3 clientes em atraso · R$ 18.740 em cobranças preparadas" },
  { id: "task-carlos-1", employeeId: "carlos", title: "Cotar materiais da obra Pinheiros", description: "Comparar preço e prazo de cimento, aço e blocos.", priority: "alta", status: "executando", dueAt: "Amanhã, 12:00", requiresApproval: true, createdAt: "Hoje, 09:10" },
  { id: "task-sofia-1", employeeId: "sofia", title: "Organizar mensagens do fim de semana", description: "Classificar e responder solicitações simples.", priority: "média", status: "executando", dueAt: "Hoje, 11:00", requiresApproval: false, createdAt: "Hoje, 08:00" },
  { id: "task-lucas-1", employeeId: "lucas", title: "Reativar leads sem contato", description: "Identificar leads parados há mais de 14 dias.", priority: "média", status: "concluída", dueAt: "Ontem", requiresApproval: false, createdAt: "Ontem, 14:20", result: "7 oportunidades identificadas e organizadas para follow-up." },
];

export const approvals: Approval[] = [
  { id: "approval-1", taskId: "task-ana-1", employeeId: "ana", title: "Enviar 3 cobranças", description: "Cobranças preparadas para clientes com pagamentos vencidos há mais de 5 dias.", impact: "Recuperação potencial de R$ 18.740 sem alteração de valores ou multas.", risk: "médio", status: "pendente", amount: 18740, requestedAt: "Hoje, 09:24" },
  { id: "approval-2", taskId: "task-carlos-1", employeeId: "carlos", title: "Confirmar fornecedor recomendado", description: "Selecionar Concreforte para o lote de cimento da obra Pinheiros.", impact: "Economia prevista de R$ 2.340 e entrega dois dias antes.", risk: "médio", status: "pendente", amount: 28650, requestedAt: "Hoje, 09:51" },
];

export const activities: Activity[] = [
  { id: "act-1", employeeId: "carlos", taskId: "task-carlos-1", title: "Compra enviada para aprovação", description: "Carlos recomendou a proposta com melhor equilíbrio entre preço e prazo.", type: "aprovação", createdAt: "09:51" },
  { id: "act-2", employeeId: "carlos", taskId: "task-carlos-1", title: "Fornecedor recomendado", description: "Concreforte ficou 7,6% abaixo da média das propostas.", type: "ferramenta", createdAt: "09:46" },
  { id: "act-3", employeeId: "ana", taskId: "task-carlos-1", title: "Orçamento confirmado", description: "Ana validou disponibilidade de R$ 32 mil para materiais.", type: "colaboração", createdAt: "09:38" },
  { id: "act-4", employeeId: "ana", taskId: "task-ana-1", title: "Cobranças preparadas", description: "3 cobranças somando R$ 18.740 aguardam sua aprovação.", type: "aprovação", createdAt: "09:24" },
  { id: "act-5", employeeId: "ana", taskId: "task-ana-1", title: "Contas analisadas", description: "12 vencimentos foram classificados por data, valor e risco.", type: "tarefa", createdAt: "09:18" },
  { id: "act-6", employeeId: "sofia", taskId: "task-sofia-1", title: "42 clientes atendidos", description: "39 dúvidas resolvidas e 3 casos encaminhados ao time humano.", type: "tarefa", createdAt: "08:55" },
];

export const integrations: Integration[] = [
  { id: "google-workspace", provider: "google-workspace", name: "Google Workspace", description: "Gmail e Google Calendar em uma única conexão", category: "Produtividade", connected: false, initials: "GW", status: "disconnected" },
  { id: "whatsapp", name: "WhatsApp", description: "Mensagens e atendimento aos clientes", category: "Comunicação", connected: true, initials: "WA" },
  { id: "drive", name: "Google Drive", description: "Documentos e arquivos da empresa", category: "Arquivos", connected: true, initials: "GD" },
  { id: "erp", name: "ERP Alpha", description: "Financeiro, compras e cadastros", category: "Operação", connected: true, initials: "ER" },
  { id: "crm", name: "CRM", description: "Leads, oportunidades e clientes", category: "Comercial", connected: false, initials: "CR" },
  { id: "n8n", name: "n8n", description: "Automações e processos internos", category: "Automação", connected: false, initials: "N8" },
  { id: "webhook", name: "Webhook", description: "Conecte qualquer sistema por eventos", category: "Desenvolvimento", connected: false, initials: "WH" },
];

export const financialAccounts: FinancialAccount[] = [
  { id: "account-sample-1", customerName: "Incorporadora Vale", document: "NF-1042", amount: 8200, dueDate: "2026-08-04", status: "overdue", source: "sample", createdAt: "Demonstração" },
  { id: "account-sample-2", customerName: "Residencial Aurora", document: "NF-1048", amount: 5940, dueDate: "2026-08-01", status: "overdue", source: "sample", createdAt: "Demonstração" },
  { id: "account-sample-3", customerName: "Construtora Pátio", document: "NF-1060", amount: 12900, dueDate: "2026-08-09", status: "open", source: "sample", createdAt: "Demonstração" },
];

export const initialDemoState: DemoState = { employees, tasks, approvals, activities, integrations, financialAccounts, financialCollectionEvents: [], financialDocuments: [], financialEntries: [], anaAuditEvents: [], financialHandoffs: [], financialBudgets: [], procurementRequests: [], suppliers: [], supplierQuotes: [], supportCases: [], salesLeads: [] };
